[package]
name = "txt2po"
version = "0.1.20200130"
authors = ["David Jimenez <davidjimenez75@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
shell-words = "0.1.0"